### ISSUE TITLE
Include LICENSE in PyPI package

### ISSUE THREAD

**Issue by philip-khor** [numeristical/splinecalib#1]
LICENSE file is not included in PyPI distribution 

https://github.com/conda-forge/staged-recipes/pull/18700#discussion_r854517162_

**Comment by blucena** [comment]
Hi Philip,  thanks for pointing this out.  What's the easiest way to fix this.  I chose an MIT license for the github, but I must have missed a step to make it go through to the package.  If you know the steps to follow please let me know - otherwise I'll research and try to figure it out.

**Comment by blucena** [comment]
Thanks Philip!
